#ifndef _MAIBU_RES_H
#define _MAIBU_RES_H
#define  BMP_SNAKE_TITLE  5001
#define  BMP_SNAKE_BLACK_BOTTOM  5002
#define  BMP_SNAKE_GAME_OVER  5003
#define  RES_BITMAP_WATCHFACE_NUMBER_BIG_0  5004
#define  RES_BITMAP_WATCHFACE_NUMBER_BIG_1  5005
#define  RES_BITMAP_WATCHFACE_NUMBER_BIG_2  5006
#define  RES_BITMAP_WATCHFACE_NUMBER_BIG_3  5007
#define  RES_BITMAP_WATCHFACE_NUMBER_BIG_4  5008
#define  RES_BITMAP_WATCHFACE_NUMBER_BIG_5  5009
#define  RES_BITMAP_WATCHFACE_NUMBER_BIG_6  5010
#define  RES_BITMAP_WATCHFACE_NUMBER_BIG_7  5011
#define  RES_BITMAP_WATCHFACE_NUMBER_BIG_8  5012
#define  RES_BITMAP_WATCHFACE_NUMBER_BIG_9  5013
#define  RES_BITMAP_WATCHFACE_NUMBER_LIT_0  5014
#define  RES_BITMAP_WATCHFACE_NUMBER_LIT_1  5015
#define  RES_BITMAP_WATCHFACE_NUMBER_LIT_2  5016
#define  RES_BITMAP_WATCHFACE_NUMBER_LIT_3  5017
#define  RES_BITMAP_WATCHFACE_NUMBER_LIT_4  5018
#define  RES_BITMAP_WATCHFACE_NUMBER_LIT_5  5019
#define  RES_BITMAP_WATCHFACE_NUMBER_LIT_6  5020
#define  RES_BITMAP_WATCHFACE_NUMBER_LIT_7  5021
#define  RES_BITMAP_WATCHFACE_NUMBER_LIT_8  5022
#define  RES_BITMAP_WATCHFACE_NUMBER_LIT_9  5023
#endif
