#ifndef _MAIBU_RES_H
#define _MAIBU_RES_H
#define  IMAGE_ICON  5001
#define  RES_BITMAP_HEALTH_INTRO_1  5002
#define  RES_BITMAP_HEALTH_INTRO_2  5003
#define  RES_BITMAP_HEALTH_INTRO_3  5004
#define  RES_BITMAP_HEALTH_INTRO_4  5005
#define  RES_BITMAP_HEALTH_STAND_ALARM  5006
#define  RES_BITMAP_HEALTH_CUP  5007
#endif
